# Generated by Django 2.1.2 on 2018-10-10 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='posts',
            table='posts',
        ),
    ]
