# Generated by Django 2.1.2 on 2018-10-12 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profiles',
            table='profile',
        ),
    ]
